Initial refactorings for v7, including collector v111.

diff --git a/jobs/appfirst/templates/shell/env.erb b/jobs/appfirst/templates/shell/env.erb
--- a/jobs/appfirst/templates/shell/env.erb
+++ b/jobs/appfirst/templates/shell/env.erb
@@ -1,24 +1,35 @@
 #!/usr/bin/env bash
-
-set -e
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
 vmName="<%= name %>" # BOSH VM name
 vmIndex="<%= index %>" # index within cluster
 vmFullName="${vmName}/${vmIndex}" # full job name
+jobName="appfirst"
 
-LANG=en_US.UTF-8
+mkdir -p "/var/vcap/sys/log/${jobName}"
+exec &> >(tee -a "/var/vcap/sys/log/${jobName}/${jobName}.log") # STD{OUT,ERR}
+echo -e "$(date +'%Y-%m-%dT%H:%M:%S') $(whoami) > $0 $*"
+
+source /var/vcap/jobs/${jobName}/shell/functions
+
+<% if p('appfirst.debug') == "true" %>turn_debugging_on<% end %>
+
+userName="vcap"
+groupName="vcap"
+LANG="en_US.UTF-8"
 HOME="${HOME:-"/home/vcap"}"
-job="appfirst"
-jobPath="/var/vcap/jobs/${job}"
-pkgPath="/var/vcap/packages/${job}"
-runPath="/var/vcap/sys/run/${job}"
-logPath="/var/vcap/sys/log/${job}"
-tmpPath="/var/vcap/sys/tmp/${job}"
-storePath="/var/vcap/store/${job}"
-dataPath="/var/vcap/store/${job}/data"
+jobPath="/var/vcap/jobs/${jobName}"
+pkgPath="/var/vcap/packages/${jobName}"
+runPath="/var/vcap/sys/run/${jobName}"
+logPath="/var/vcap/sys/log/${jobName}"
+tmpPath="/var/vcap/sys/tmp/${jobName}"
+storePath="/var/vcap/store/${jobName}"
+dataPath="/var/vcap/store/${jobName}/data"
 pidFile="${runPath}/afcollector.pid"
 LD_LIBRARY_PATH="${pkgPath}/lib"
 binary="${pkgPath}/bin/afcollector"
+export LANG HOME LD_LIBRARY_PATH
 
 # NOTE: It is important for lib Path to be outside BOSH dir on system so that 
 # it does not break any processes when bosh nukes or changes the job directory
@@ -52,11 +63,6 @@ case "${arch}" in
   (*) fail "Only x86_64 for afcollector is supported in BOSH at this time." ;;
 esac
 
-# Add all packages' /bin & /sbin into $PATH
-for pkg_bin_path in $(ls -d /var/vcap/packages/*/*bin)
-do PATH="${pkg_bin_path}:${PATH}"
-done
-
 # JMX collector will only be enabled if the property is set explicitely to 'true' in the manifest.
 enableJMX=<%= p('appfirst.jmx_collector_enabled') %>
 if [[ ${enableJMX:-"false"} == "true" ]]
@@ -68,25 +74,9 @@ export vmName vmIndex vmFullName job jobPath serverTags logFiles \
   runPath logPath tmpPath storePath wrapPath dataPath pidFile \
   PATH LANG HOME LD_LIBRARY_PATH JMXCOLLECTOR
 
-paths=(
-"${jobPath}" "${runPath}" "${logPath}" "${tmpPath}" "${storePath}" 
-"${wrapPath}" "${dataPath}"
-)
+add_packages_to_path
 
-# Ensure all paths exist, are owned by vcap:vcap and are executable
-for _path in "${paths[@]}"
-do
-  if ! [[ -d ${_path} ]]
-  then
-    mkdir -p "${_path}" 
-    chown vcap:vcap "${_path}" 
-    chmod 0775 "${_path}"
-  fi
-done
-
-# Redirect all output to log file.
-exec 1>> "${logPath}/${job}.log"
-exec 2>> "${logPath}/${job}.log"
+configure_job_paths
 
 echo -e "$(date +'%Y-%m-%dT%H:%M:%S')\$> $0 $*"
 
